title: Connecting a PIR sensor attempt 2
hero_image: images/banner.png
subtitle: Connecting a PIR sensor attempt 2 subtitle
description: Connecting a PIR sensor attempt 2 description
published: false
steps:
  - title: Step one
    duration: 60
