title: Connecting a PIR sensor attempt 2
hero_image: images/banner.png
subtitle: Connecting a PIR sensor attempt 2 subtitle
description: Connecting a PIR sensor attempt 2 description
listed: false
ingredient: true
curriculum:
interests:
technologies:
duration: 1
steps:
  - title: Step one
